name: aws_cognito_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  amazon_cognito_identity_dart_2: ^3.1.1
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.1 
  flag: ^7.0.0
  image_picker: ^1.0.4
  path_provider: ^2.0.15
  flex_color_picker: ^3.2.2
  uuid: ^3.0.5
  shared_preferences: ^2.0.0
  connectivity_plus: ^4.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_spinkit: ^5.2.0
  archive: ^3.3.7
  get: ^4.6.5
  http: ^1.1.0
  permission_handler: ^11.0.0
  localstorage: ^4.0.0+1
  universal_html: ^2.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.2
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/json/mock_restaurant.json
    - assets/images/
    - assets/images/ingredients/
    - assets/images/pizza/
    - assets/images/przystawki/
    - assets/images/salatki/
    - assets/images/zupy/
    - assets/images/dania_glowne/
    - assets/images/ryby/
    - assets/images/dzieci/
    - assets/images/logowanie/
    - .env
  fonts:
  - family: CormorantGaramond     
    fonts:
      - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Regular.ttf
      - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Bold.ttf
      - asset: assets/fonts/CormorantGaramond/CormorantGaramond-Light.ttf
  - family: RobotoCondensed
    fonts:
      - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
  - family: Montserrat     
    fonts:
      - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
  - family: Poppins     
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf